plugins { id 'com.android.application' }

android {
    namespace 'com.untitled1ne.yezdibridge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.untitled1ne.yezdibridge'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '0.7-native-maps'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-maps:19.0.0'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
}
